\hypertarget{classpip_1_1__internal_1_1exceptions_1_1CommandError}{}\doxysection{pip.\+\_\+internal.\+exceptions.\+Command\+Error Class Reference}
\label{classpip_1_1__internal_1_1exceptions_1_1CommandError}\index{pip.\_internal.exceptions.CommandError@{pip.\_internal.exceptions.CommandError}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Command\+Error\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=217pt]{classpip_1_1__internal_1_1exceptions_1_1CommandError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Command\+Error\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=217pt]{classpip_1_1__internal_1_1exceptions_1_1CommandError__coll__graph}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raised when there is an error in command-line arguments\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
inventaria\+\_\+env/lib/python3.\+10/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
