\hypertarget{classnumpy_1_1core_1_1__exceptions_1_1TooHardError}{}\doxysection{numpy.\+core.\+\_\+exceptions.\+Too\+Hard\+Error Class Reference}
\label{classnumpy_1_1core_1_1__exceptions_1_1TooHardError}\index{numpy.core.\_exceptions.TooHardError@{numpy.core.\_exceptions.TooHardError}}


Inheritance diagram for numpy.\+core.\+\_\+exceptions.\+Too\+Hard\+Error\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=234pt]{classnumpy_1_1core_1_1__exceptions_1_1TooHardError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for numpy.\+core.\+\_\+exceptions.\+Too\+Hard\+Error\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=234pt]{classnumpy_1_1core_1_1__exceptions_1_1TooHardError__coll__graph}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}max_work was exceeded.

This is raised whenever the maximum number of candidate solutions 
to consider specified by the ``max_work`` parameter is exceeded.
Assigning a finite number to max_work may have caused the operation 
to fail.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
inventaria\+\_\+env/lib/python3.\+10/site-\/packages/numpy/core/\+\_\+exceptions.\+py\end{DoxyCompactItemize}
