\hypertarget{classpip_1_1__internal_1_1exceptions_1_1ConfigurationError}{}\doxysection{pip.\+\_\+internal.\+exceptions.\+Configuration\+Error Class Reference}
\label{classpip_1_1__internal_1_1exceptions_1_1ConfigurationError}\index{pip.\_internal.exceptions.ConfigurationError@{pip.\_internal.exceptions.ConfigurationError}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Configuration\+Error\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=272pt]{classpip_1_1__internal_1_1exceptions_1_1ConfigurationError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Configuration\+Error\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=217pt]{classpip_1_1__internal_1_1exceptions_1_1ConfigurationError__coll__graph}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}General exception in configuration\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
inventaria\+\_\+env/lib/python3.\+10/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
